### PR TITLE
Set deployment target to iOS 9 on aerogear-ios-otp

### PR DESCRIPTION
**Pull request by danielpassos**
Relates issues:

* [AGIOS-596](https://issues.jboss.org/browse/AGIOS-596) - Set deployment target to iOS 9 on aerogear-ios-otp

### CODE REVIEW

**Comment by jcesarmobile** [comment]
You forgot to change the iOS version on the .podspec file

**Comment by danielpassos** [comment]
Done!

**Comment by jcesarmobile** [comment]
It's not correctly set for the targets, you have to do it on the Build settings tab as there is no general tab.

Also, can you update the project to Xcode 9 recommended settings?

**Comment by danielpassos** [comment]
@jcesarmobile I have updated the project recommendations and I see not warning :/

**Comment by jcesarmobile** [comment]
I've sent a [PR](https://github.com/danielpassos/aerogear-ios-otp/pull/1) to your branch because one of the new recommended settings is not allowing the tests to run from Xcode.

The deprecate warnings I see are on the test classes
`AGClockTests.m:30:84: 'NSGregorianCalendar' is deprecated: first deprecated in iOS 8.0 - Use NSCalendarIdentifierGregorian instead`

**Pull request merged**
